# Plugin Definition below. This is essentially a valid helm values file that will be merged
# with the other vcluster values during vcluster create or helm install.
plugin:
  prometheus-operator-resources:
    image: ghcr.io/codefresh-contrib/vcluster-prometheus-operator-plugin:v1-main
    imagePullPolicy: IfNotPresent
    rbac:
      role:
        extraRules:
          - apiGroups: ["monitoring.coreos.com"]
            resources: ["servicemonitors","podmonitors"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]
      clusterRole:
        extraRules:
          - apiGroups: ["apiextensions.k8s.io"]
            resources: ["customresourcedefinitions"]
            verbs: ["get", "list", "watch"]
          - apiGroups: ["monitoring.coreos.com"]
            resources: ["servicemonitors","podmonitors"]
            verbs: ["create", "delete", "patch", "update", "get", "list", "watch"]

# Make sure the cluster role is enabled or otherwise the plugin won't be able to watch custom
# resource definitions.
rbac:
  clusterRole:
    enabled: true
