apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: sm-with-ns-selector
spec:
  steps:
  - try:
    - assert:
        resource:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: sm-with-ns-selector-x-default-x-vcluster
            namespace: default
          spec:
            namespaceSelector: {}
            selector:
              matchExpressions:
              - key: vcluster.loft.sh/namespace
                operator: In
                values:
                - my-virtual-namespace
              matchLabels:
                app: example-app
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: sm-without-ns-selector
spec:
  steps:
  - try:
    - assert:
        resource:
          apiVersion: monitoring.coreos.com/v1
          kind: ServiceMonitor
          metadata:
            name: sm-without-ns-selector-x-default-x-vcluster
            namespace: default
          spec:
            namespaceSelector: {}
            selector:
              # Resources are deployed to default namespace of vcluster
              matchExpressions:
              - key: vcluster.loft.sh/namespace
                operator: In
                values:
                - default
              matchLabels:
                app: example-app
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pm-with-ns-selector
spec:
  steps:
  - try:
    - assert:
        resource:
          apiVersion: monitoring.coreos.com/v1
          kind: PodMonitor
          metadata:
            name: pm-with-ns-selector-x-default-x-vcluster
            namespace: default
          spec:
            namespaceSelector: {}
            selector:
              matchExpressions:
              - key: vcluster.loft.sh/namespace
                operator: In
                values:
                - my-virtual-namespace
              matchLabels:
                app: example-app
---
apiVersion: chainsaw.kyverno.io/v1alpha1
kind: Test
metadata:
  name: pm-without-ns-selector
spec:
  steps:
  - try:
    - assert:
        resource:
          apiVersion: monitoring.coreos.com/v1
          kind: PodMonitor
          metadata:
            name: pm-without-ns-selector-x-default-x-vcluster
            namespace: default
          spec:
            namespaceSelector: {}
            selector:
              matchExpressions:
              - key: vcluster.loft.sh/namespace
                operator: In
                values:
                - default
              matchLabels:
                app: example-app
