apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-with-ns-selector
  namespace: default
  labels:
    team: frontend
spec:
  namespaceSelector:
    any: false
    matchNames:
    - my-virtual-namespace
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: sm-without-ns-selector
  namespace: default
  labels:
    team: frontend
spec:
  namespaceSelector: {}
  selector:
    matchLabels:
      app: example-app
  endpoints:
  - port: web
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: pm-with-ns-selector
  namespace: default
  labels:
    team: frontend
spec:
  namespaceSelector:
    any: false
    matchNames:
    - my-virtual-namespace
  selector:
    matchLabels:
      app: example-app
